### PR TITLE
Reconnect if the mqtt connection drops

### PR DESCRIPTION
**Pull request by roleoroleo**

### CODE REVIEW

**Comment by ping-localhost** [comment]
@TheCrypt0 Any chance you could look at this? This is quite an annoying issue. 😢

**Comment by tinysnake** [comment]
wow, what a easy fix! hope that works! good job!

**Comment by ping-localhost** [comment]
@TheCrypt0 If I can help in any way, please let me know

**Comment by ping-localhost** [comment]
Pinging @TheCrypt0 again.

**Comment by ping-localhost** [comment]
Pretty sure this project should be seen as abandoned. @TheCrypt0 clearly doesn't care anymore.

**Comment by TheCrypt0** [comment]
Hi, I must have missed the PR!
I currently don't have much time to test them, but if I can get some confirmations that the various changes work, I'll merge.

@roleoroleo @ping-localhost

**Comment by roleoroleo** [comment]
Sorry @TheCrypto, I forgot to create a different branch after the 1st commit "Reconnect if the mqtt connection drops".
Probably the following commits are not applicable to this model of yi cam.
I think it's better that we close this PR and I will open a new one with the correct patch.

**Comment by roleoroleo** [comment]
See this: https://github.com/TheCrypt0/mqttv4/pull/3

**Pull request closed without merging**
